# Generated by Django 5.0.6 on 2024-05-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
