# Generated by Django 4.2.7 on 2024-05-13 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesurement', '0001_initial'),
        ('product', '0005_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uom_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesurement.mesurement'),
        ),
        migrations.DeleteModel(
            name='Uom',
        ),
    ]
